[workspace]
authors = ["conda steering council <steering@conda.org>"]
channels = ["conda-forge"]
name = "conda-dot-org"
platforms = ["linux-64", "osx-64", "win-64", "linux-aarch64", "osx-arm64"]
version = "0.1.0"

[tasks]
install = "npm i"
start = { cmd = "npm start", depends-on = ["install"] }
build = { cmd = "npm build", depends-on = ["install"] }
serve = { cmd = "npm serve", depends-on = ["install"] }
lint = { cmd = "npm lint", depends-on = ["install"] }
update-news = { cmd = "npm update-news", depends-on = ["install"] }
banner = { cmd = "npm banner", depends-on = ["install"] }

[dependencies]
python = "*"
nodejs = "*"
"ruamel.yaml" = "*"
jinja2 = "*"
stylelint = "*"
