name: Republish site

on:
  schedule:
    - cron: "0 0 * * 4" # Every Thursday (after biweekly Wednesdays)
  workflow_dispatch:

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - run: >
          curl -X POST -d '{}' 
          https://api.netlify.com/build_hooks/${{ secrets.NETLIFY_BUILD_HOOK_ID }}?trigger_title=Triggered+by+Github+Actions
